classdef BrainCamSystem < SubSystem
  % ------------------------------------------------------------------------------
  % BrainCamSystem
  % FrameSynx toolbox
  % 2/8/2010
  % Mark Bucklin
  % ------------------------------------------------------------------------------
  %
  % The BrainCamSystem class subclasses the SubSystem class, which lends
  % methods for synchronization and data-management. It serves as an
  % interface to a camera object (object of any class derived from CAMERA),
  % and also to synchronized illumination objects, and the data-files
  % generated by the image acquisition. In other words, it controls the
  % camera in uniform way, and stores data from the camera (images in this
  % case) in the same way one would store data using, say, an
  % 'EyetrackerSystem' class. Refer to SubSystem.m for more documentation
  %
  % EXAMPLE:
  %  Create a BrainCamSystem, start it, save all images for 10 minutes
  %
  % >> camsys = BrainCamSystem;
  % >> camsys.start()
  % >> camsys.trigger();
  % >> tic
  % >> while toc<600, pause(5), camsys.saveDatafile()
  %
  %
  % BrainCamSystem Properties:
  %   experimentSyncObj - usually a BehaviorSystem object
  %   trialSyncObj - usually a BehaviorSystem object
  %   frameSyncObj - usually the videoInputObj
  %   videoInputObj - a DalsaCamera or WebCamera
  %   illuminationObj - IlluminationControlInterface
  %   cameraClass - string: 'DalsaCamera'
  %   frameSyncMode - 'auto' or 'external'
  %   externalFrameSyncPeriod - for reduced frame rate
  %
  %
  %
  % SubSystem Methods:
  %   start - gets everything ready for acquisition
  %   trigger - triggers the camera to begin acquiring
  %   stop - stops acquisition
  %   delete - deletes the object
  %
  % See also SUBSYSTEM, BEHAVIORSYSTEM, DATAFILE, SYSTEMSYNCHRONIZER,
  % DATAACQUISITION, FRAMESYNX, CAMERA, MATLABCOMPATIBLECAMERA, VIDEOFILE,
  % DALSACAMERA, WEBCAMERA
  %
  
  
  
  
  
  
  properties
	 experimentSyncObj %Must broadcast 'ExperimentStart' and 'ExperimentStop' events
	 trialSyncObj %Must broadcast the 'NewTrial' event
	 frameSyncObj %Must broadcast the 'FrameAcquired' event
  end
  properties
	 videoInputObj %Used to drive framesyncing if frameSyncMode is 'auto', otherwise its the frameSyncObj that generates the sync
	 frameSyncMode % 'auto' or 'external'
	 externalFrameSyncPeriod % defaults to 4 for a WebCamera synchronized with the DalsaCamera doing rrgg
	 % 		currentDataFile
	 % 		sessionPath
	 % 		systemName
	 % 		savedDataFiles
  end
  properties (SetObservable, GetObservable) % CAMERA PROPERTIES
	 camAdapter % 'coreco' or 'winvideo'
	 deviceID %  1
	 videoFormat
	 triggerMode
	 triggerConfiguration
	 exposureTime
	 previewFigure
	 previewAxes
	 previewImageObj
  end
  properties (SetAccess = protected)
	 % 	 videoInputObj
  end
  properties (Hidden)
	 % 				frameSyncListener
	 % 				experimentStateListener
	 % 				trialStateListener
	 % 				framesAcquired
	 % 				nDataFiles
	 % 				experimentRunning
	 % 				default
  end
  
  
  
  
  
  events
	 FrameAcquired
  end
  
  
  
  
  
  methods % SETUP
	 function obj = BrainCamSystem(varargin)
		if nargin > 1
		  for k = 1:2:length(varargin)
			 obj.(varargin{k}) = varargin{k+1};
		  end
		end
	 end
	 function setup(obj)
		obj.defineDefaults()
		obj.checkProperties()
		obj.createSystemComponents()
	 end
	 function defineDefaults(obj)
		persistent camnum
		if isempty(camnum)
		  camnum = 1;
		else
		  camnum = camnum+1;
		end
		obj.defineDefaults@SubSystem;
		% 		obj.default.systemName =  ['BrainCamSystem_',num2str(camnum)];
		% 		obj.default.frameSyncMode = 'auto';
		% 		obj.default.externalFrameSyncPeriod = 1;
	 end
	 function checkProperties(obj)
		obj.framesAcquired = 0;
		obj.nDataFiles = 0;
		obj.savedDataFiles = VideoFile.empty(1,0);
		obj.currentDataFileSet = VideoFile.empty(1,0);
		if ~isempty(obj.experimentSyncObj)
		  if ~isempty(obj.experimentStateListener)
			 obj.experimentStateListener.Enabled = false;
		  end
		  if ~isempty(obj.trialStateListener)
			 obj.trialStateListener.Enabled = false;
		  end
		  obj.trialStateListener = addlistener(obj.trialSyncObj,...
			 'NewTrial',@(src,evnt)trialStateChangeFcn(obj,src,evnt));
		  obj.trialStateListener.Enabled = false;
		  obj.experimentStateListener = addlistener(obj.experimentSyncObj,...
			 'ExperimentStart',@(src,evnt)experimentStateChangeFcn(obj,src,evnt));
		  addlistener(obj.experimentSyncObj,...
			 'ExperimentStop',@(src,evnt)experimentStateChangeFcn(obj,src,evnt));
		  obj.experimentStateListener.Enabled = true;
		end
		obj.checkProperties@SubSystem;
	 end
	 function createSystemComponents(obj)
		persistent camnum
		if isempty(camnum)
		  camnum = 1;
		else
		  camnum = camnum+1;
		end
		% Video Input
		info = imaqhwinfo;
		if isempty(obj.camAdapter)
		  if length(info.InstalledAdaptors) > 1
			 output = listdlg('PromptString','Select an Adapter:',...
				'SelectionMode','single',...
				'ListString',info.InstalledAdaptors);
			 if output
				obj.camAdapter = info.InstalledAdaptors{output};
			 else
				obj.camAdapter = 'winvideo';
			 end
		  else
			 obj.camAdapter = info.InstalledAdaptors{1};
		  end
		end
		adapterinfo = imaqhwinfo(obj.camAdapter);
		if isempty(obj.deviceID)
		  obj.deviceID = 1;
		  if length(adapterinfo.DeviceIDs) > 1
			 output = listdlg('PromptString','Select an Device:',...
				'SelectionMode','single',...
				'ListString',adapterinfo.DeviceIDs);
			 if output
				obj.deviceID = adapterinfo.DeviceIDs{output};
			 else
				obj.deviceID = 1;
			 end
		  else
			 obj.deviceID = 1;
		  end
		end
		devinfo = adapterinfo.DeviceInfo(obj.deviceID);
		if isempty(obj.videoFormat)
		  if length(devinfo.SupportedFormats) == 1
			 obj.videoFormat = devinfo.SupportedFormats{1};
		  end
		  if length(devinfo.SupportedFormats)>1
			 output = listdlg('PromptString','Select a Format:',...
				'SelectionMode','single',...
				'ListString',devinfo.SupportedFormats,...
				'ListSize',[400 300]);
			 if output
				obj.videoFormat = devinfo.SupportedFormats{output};
			 else
				obj.videoFormat = devinfo.DefaultFormat;
			 end
		  end
		  % TRIGGER CONFIGURATION (moved from DcamCamera)
		  if isempty(obj.triggerConfiguration)
			 obj.queryTriggerConfigFcn();
		  end
		end
		obj.videoInputObj = videoinput(...
		  obj.camAdapter,obj.deviceID,obj.videoFormat);
		set(obj.videoInputObj,...
		  'framespertrigger',inf,...
		  'name',devinfo.DeviceName,...
		  'FramesAcquiredFcnCount',1,...
		  'FramesAcquiredFcn',@(src,evnt)frameAcquiredFcn(obj,src,evnt));
		if isempty(obj.triggerMode)
		  obj.triggerMode = 'manual';
		end
		if ~isempty(obj.triggerConfiguration)
		  triggerconfig(obj.videoInputObj,obj.triggerConfiguration);
		else
		  triggerconfig(obj.videoInputObj,'manual');
		end
		if isempty(obj.frameSyncMode)
		  obj.frameSyncMode = 'auto'; % added 7/22
		end
		% Define Listener
		if strcmpi(obj.frameSyncMode,'auto')
		  obj.frameSyncListener = addlistener(obj,...
			 'FrameAcquired',@(src,evnt)frameAcquiredFcn(obj,src,evnt));
		end
		% 		obj.videoInputObj.frameSyncMode = obj.frameSyncMode;
	 end
	 function queryTriggerConfigFcn(obj)
		if ~isempty(obj.videoInputObj) && isvalid(obj.videoInputObj)
		  vti = triggerinfo(obj.videoInputObj);
		  trigfields = fields(vti);
		  for k = 1:numel(vti)
			 trigsetting = '';
			 for f = 1:numel(trigfields)
				trigfieldname = trigfields{f};
				trigsetting = sprintf('%s%s:%s|',trigsetting, trigfieldname,vti(k).(trigfieldname));
			 end
			 trigSettingList{k,1} = trigsetting;
		  end
		  output = listdlg('PromptString','Select a Trigger Configuration:',...
			 'SelectionMode','single',...
			 'ListString',trigSettingList,...
			 'ListSize',[700 300],...
			 'Name','Camera TriggerConfig',...
			 'InitialValue',4);
		  obj.triggerConfiguration = vti(output);
		  switch obj.triggerConfiguration.TriggerType
			 case 'immediate'
				obj.triggerMode = 'auto';
			 case 'manual'
				obj.triggerMode = 'manual';
			 case 'hardware'
				obj.triggerMode = 'hardware';
			 otherwise
				obj.triggerMode = 'manual';
		  end
		  % Set triggerMode to auto for software trigger
		end
	 end
	 function resetTrigConfig(obj,varargin)
		if ~obj.isvalid
		  setup(obj)
		end
		if nargin < 2
		  obj.queryTriggerConfigFcn;
		else
		  obj.triggerConfiguration = varargin{1};
		end
		try
		  stop(obj)
		  triggerconfig(obj.videoInputObj, obj.triggerConfiguration)
		catch me
		  warning(me.message)
		  obj.queryTriggerConfigFcn;
		end
		start(obj)
	 end
  end
  methods % CONTROL
	 function start(obj)
		obj.updateExperimentName();
		obj.updateExperimentPath();
		% 		fprintf('%s: Preparing %s for Video-Acquisition\n',...
		% 		  obj.systemName,obj.videoInputObj.name);
		if ~isrunning(obj.videoInputObj)
		  start(obj.videoInputObj);
		end
		if ~isempty(obj.experimentStateListener)
		  obj.experimentStateListener.Enabled = true;
		end
		if ~isempty(obj.trialStateListener)
		  obj.trialStateListener.Enabled = true;
		end
		if isempty(obj.frameSyncObj)
		  obj.frameSyncObj = obj.videoInputObj; % default auto sync
		end
		obj.ready = true;
	 end
	 function trigger(obj)
		if ~isready(obj)
		  obj.start();
		end
		obj.updateExperimentName();
		% 		obj.videoInputObj.imageDataDirectory = obj.currentDataSetPath;
		% added 7/15/2014
		if ~isempty(obj.frameSyncListener)
		  obj.frameSyncListener.Enabled = true;
		end
		
		if ~islogging(obj.videoInputObj)
		  trigger(obj.videoInputObj);
		  % 		  fprintf('%s: Triggering %s Video-Acquisition\n',...
		  % 			 obj.systemName,obj.videoInputObj.name);
		end
		if ~isempty(obj.trialStateListener)
		  obj.trialStateListener.Enabled = true;
		end
		
		%       if ~isempty(obj.currentDataFileSet)
		%         obj.currentDataFileSet = VideoFile.empty(1,0);
		%         obj.nDataFiles = 0;
		%       end
	 end
	 function stop(obj)
		fprintf('Stopping %s Video-Acquisition\n',obj.videoInputObj.name);
		stop(obj.videoInputObj);
		if ~isempty(obj.currentDataFile) ...
			 && isopen(obj.currentDataFile) ...
			 && ~issaved(obj.currentDataFile)
		  obj.saveDataFile;
		end
		if ~isempty(obj.trialStateListener)
		  obj.trialStateListener.Enabled = false;
		end
		if ~isempty(obj.currentDataFileSet)
		  obj.saveDataSet();
		  obj.clearDataSet();
		end
		obj.currentDataFile = VideoFile.empty(1,0);
		lastwarn('')
		% 						start(obj.videoInputObj)
	 end
	 function syncExternal(obj)
		% 		persistent data	syncframe
		% 		try
		% 		  if isempty(obj.currentDataFile)
		% 			 % called on first frame
		% 			 obj.currentDataFile = VideoFile('rootPath',obj.currentDataSetPath);
		% 		  end
		% 		  if isempty(syncframe)
		% 			 syncframe = 1;
		% 		  else
		% 			 syncframe = syncframe + 1;
		% 		  end
		% 		  if syncframe==obj.externalFrameSyncPeriod
		% 			 data = getSyncFrame(obj.videoInputObj);
		% 			 obj.framesAcquired = obj.framesAcquired + 1;
		% 			 % Get Info Structure
		% 			 info.FrameNumber = obj.framesAcquired;
		% 			 info.FrameTime = data.time;
		% 			 info.AbsTime = datenum(data.meta.AbsTime);
		% 			 if ~isempty(obj.illuminationObj)
		% 				info.Channel = getData(obj.illuminationObj,1);
		% 			 end
		% 			 % may need to check frame number?
		% 			 data = data.vid;
		% 			 if isclosed(obj.currentDataFile)
		% 				if ~issaved(obj.currentDataFile)
		% 				  obj.saveDataFile;
		% 				  % if file closes somehow, it will save on the next frame and open a new file
		% 				  % e.g. if someone access data while it's open, it will close... ?
		% 				end
		% 				obj.currentDataFile = VideoFile('rootPath',obj.currentDataSetPath);
		% 			 end
		% 			 addFrame2File(obj.currentDataFile,data,info);
		% 			 syncframe = 0;
		% 		  end
		% 		catch me
		% 		  warning(me.message)
		% 		  disp(me.stack(1))
		% 		end
	 end
  end
  methods % EVENT RESPONSE
	 function frameAcquiredFcn(obj,src,evnt)
		info = struct('AbsTime',[],...
		  'FrameNumber',[],...
		  'RelativeFrame',[],...
		  'TriggerIndex',[]);
		try
		  % 		  if strcmpi(obj.frameSyncMode,'external') ...
		  % 				|| (src ~= obj.videoInputObj)
		  % 			 obj.syncExternal();
		  % 			 return
		  % 		  end
		  % 		  notify(obj,'FrameAcquired');
		  if isempty(obj.currentDataFile)
			 % called on first frame
			 obj.currentDataFile = VideoFile('rootPath',obj.currentDataSetPath);
		  end
		  [data,~,info] = getdata(src,1);
		  info.AbsTime = datenum(info.AbsTime);
		  obj.framesAcquired = obj.framesAcquired + 1;		  
		  if isclosed(obj.currentDataFile)
			 if ~issaved(obj.currentDataFile)
				obj.saveDataFile;
				% if file closes somehow, it will save on the next frame and open a new file
				% e.g. if someone access data while it's open, it will close... ?
			 end %
			 obj.currentDataFile = VideoFile('rootPath',obj.currentDataSetPath);
		  end
		  if ~isempty(obj.frameDataCallbackFcn)
			 try
				switch class(obj.frameDataCallbackFcn)
				  case 'char'
					 eval(obj.frameDataCallbackFcn)
				  case 'function_handle'
					 data = feval(obj.frameDataCallbackFcn,data);
				  case 'cell'
					 switch class(obj.frameDataCallbackFcn{1})
						case 'function_handle'
						  data = feval(obj.frameDataCallbackFcn{1},data,obj.frameDataCallbackFcn{2:end});
						case 'char'
						  for n = 1:numel(obj.frameDataCallbackFcn)
							 eval(obj.frameDataCallbackFcn{n});
						  end
					 end
				end
			 catch
				fprintf('frameDataCallbackFcn Error\n');
			 end
		  end
		  addFrame2File(obj.currentDataFile,data,info);
		catch me
		  [~,lastid] = lastwarn;
		  if ~strcmpi(lastid,'BrainCamSystem:frameAcquiredFcn:FrameErrorCaught')
			 warning('BrainCamSystem:frameAcquiredFcn:FrameErrorCaught',...
				'An error occured while executing the frameAcquiredFcn: \n%s\n',...
				me.message)
			 disp(me.stack(1))
		  end
		  if isempty(info)
			 info = struct.empty();
		  end
		  try, addFrame2File(obj.currentDataFile,data,info); catch, end
		end
	 end
	 function experimentStateChangeFcn(obj,src,evnt)
		switch evnt.EventName
		  case 'ExperimentStart'
			 obj.updateExperimentName();
			 obj.trigger();
		  case 'ExperimentStop'
			 obj.stop();
		end
	 end
	 function trialStateChangeFcn(obj,src,evnt)
		% 						fprintf('Frames in Imaq Memory: %i\n',get(obj.videoInputObj.videoInputObj,'FramesAvailable'))
		if ~islogging(obj.videoInputObj)
		  obj.trigger(); % trigger at start of first trial rather than experiment-start
		end
		obj.saveDataFile();
	 end
  end
  methods % SET
	 function set.experimentSyncObj(obj,bhv)
		if ~isempty(obj.experimentStateListener)
		  obj.experimentStateListener.Enabled = false;
		end
		obj.experimentSyncObj = bhv;
		obj.experimentStateListener = addlistener(obj.experimentSyncObj,...
		  'ExperimentStart',@(src,evnt)experimentStateChangeFcn(obj,src,evnt));
		addlistener(obj.experimentSyncObj,...
		  'ExperimentStop',@(src,evnt)experimentStateChangeFcn(obj,src,evnt));
		obj.experimentStateListener.Enabled = true;
	 end
	 function set.trialSyncObj(obj,bhv)
		obj.trialSyncObj = bhv;
		if ~isempty(obj.trialStateListener)
		  obj.trialStateListener.Enabled = false;
		end
		obj.trialStateListener = addlistener(obj.trialSyncObj,...
		  'NewTrial',@(src,evnt)trialStateChangeFcn(obj,src,evnt));
		obj.trialStateListener.Enabled = false;
	 end
	 function set.frameSyncObj(obj,cam)
		if cam == obj.videoInputObj % (free running camera)
		  obj.frameSyncMode = 'auto';
		  obj.frameSyncObj = obj.videoInputObj;
		else
		  obj.frameSyncMode = 'external';
		end
		if any(strcmpi(events(cam),'FrameAcquired'))
		  obj.frameSyncObj = cam;
		  if ~isempty(obj.frameSyncListener)
			 obj.frameSyncListener.Enabled = false;
		  end
		  obj.frameSyncListener = addlistener(cam,...
			 'FrameAcquired',@(src,evnt)frameAcquiredFcn(obj,src,evnt));
		else
		  warning('BrainCamSystem:set_frameSyncObj:MissingFrameAcquiredEvent',...
			 'The assigned frameSync object should have a FrameAcquired event');
		end
	 end
	 function set.frameSyncMode(obj,fsmode)
		% useless other than to print an update?!?
		switch lower(fsmode)
		  case 'auto'
			 obj.frameSyncMode = 'auto';
		  case 'external'
			 obj.frameSyncMode = 'external';
		  otherwise
			 warning('BrainCamSystem:set_frameSyncMode:Invalid','invalid setting');
		end
		fprintf('%s: frameSyncMode set to %s\n',obj.systemName,obj.frameSyncMode);
		if ~isempty(obj.videoInputObj) && isa(obj.videoInputObj,'Camera')
		  obj.videoInputObj.frameSyncMode = obj.frameSyncMode;
		end
	 end
  end
  methods % CLEANUP
	 function delete(obj)
		delete(obj.videoInputObj)
		obj.delete@SubSystem;
	 end
  end
  
  
  
  
  
  
end
















