function glow = findPixelForegroundElementWise(f, fu, fr, fd, fl, su, sr, sd, sl)

	Gu = min(min(min( f, fl), fd), fr) > max(max( sl, su), sr);
	Gr = min(min(min( f, fu), fl), fd) > max(max( su, sr), sd);
	Gd = min(min(min( f, fl), fu), fr) > max(max( sl, sd), sr);
	Gl = min(min(min( f, fu), fr), fd) > max(max( su, sl), sd);

glow = ...
	(Gu & Gr & Gd) |...
	(Gu & Gl & Gd) |...
	(Gl & Gu & Gr) |...
	(Gl & Gd & Gr);
