classdef ExperimentNamingGUI < hgsetget
		
		
		
		
		properties
				hFig
				cameraObj
				prop
				default
		end
		
		
		
		
		
		methods
				function obj = ExperimentNamingGUI(varargin)
							if nargin > 1
								for k = 1:2:length(varargin)
										obj.(varargin{k}) = varargin{k+1};
								end
						end
						obj.definePositionStructure();
						obj.defineDefaults();
						obj.buildFigure();
						set(obj.hFig,'HandleVisibility','callback');
				end
				function definePositionStructure(obj)
						sz = get(0,'MonitorPositions');
						if size(sz,1) > 1
								obj.pos.dualmonitor = true;
								obj.pos.rightmonwidth = sz(1,3)-sz(1,1);
								obj.pos.rightmonheight = sz(1,4);
								obj.pos.rightmonpos = sz(1,1:2);
								obj.pos.leftmonwidth = sz(2,3);
								obj.pos.leftmonheight = sz(2,4);
						else
								obj.pos.dualmonitor = false;
								obj.pos.monwidth = sz(1,3);
								obj.pos.monheight = sz(1,4);
						end
						obj.pos.sliderlength = 190;
						obj.pos.sliderwidth = 25;
						obj.pos.standard = [10 10];
						obj.pos.bigbutton = [90 30];
						obj.pos.medbutton = [60 20];
						obj.pos.smallbutton = [40 15];
						obj.pos.shorttext = [40 20];
						obj.pos.medtext = [60 20];
						obj.pos.longtext = [90 20];
						obj.pos.xlongtext = [120 20];
						obj.pos.panwidth1 = 110;
						
						obj.pos.campanel = [40 100 420 460];
						obj.pos.datapanel = [500 100 240 560];
						obj.pos.bhvpanel = [750 100 250 600];
						obj.pos.illumpanel = [40 590 260 100];
						if obj.pos.dualmonitor
								obj.pos.mainfig = [40 60 1000 900];
						else
								obj.pos.mainfig = [40 60 1000 900];
						end
				end
				function defineDefaults(obj)
						obj.default.maxminoffset = 4096;
						obj.default.offset = 0;
						obj.default.gain = 1;
						obj.default.maxgain = 10;
						obj.default.configFileDir = [fileparts(which('Camera')),filesep,'IFC Configuration Files'];
						obj.default.maxFR = 30;
				end
				function buildFigure(obj)
						obj.dataControlFig = figure;
						set(obj.dataControlFig,...
								'units','pixels',...
								'tag','experimentseettingspanel',...
								'menubar','none',...
								'Name','ExperimentConfiguration',...
								'numbertitle','off',...
								'resize','off',...
								'position',obj.pos.datapanel);
						% Saving Panel
						obj.dataControl.savePathPan = uipanel(obj.dataControlFig,...
								'units','pixels',...
								'tag','savefilepanel',...
								'position',[10 10 220 110],...
								'title','Save to Directory');
						obj.dataControl.saveRootChgDirButt = uicontrol(obj.dataControl.savePathPan,...
								'style','pushbutton',...
								'tag','savefilechangebutt',...
								'units','pixels',...
								'position',[10 10 90 20],...
								'string','Change Root');
						obj.dataControl.monkeyPop = uicontrol(obj.dataControl.savePathPan,...
								'style','popup',...
								'tag','monkeypop',...
								'units','pixels',...
								'position',[110 10 100 20],...
								'string',obj.default.monkeyList);
						obj.dataControl.savePathAutoName = uicontrol(obj.dataControl.savePathPan,...
								'style','checkbox',...
								'tag','saveautocheck',...
								'units','pixels',...
								'position',[10 40 120 20],...
								'value',1,...
								'string','Use Default Naming');
						if get(obj.dataControl.savePathAutoName,'value')%is checked
% 								obj.savePath = [obj.default.saveRoot,...
% 										obj.animalName,'\',...
% 										obj.animalName,datestr(date,'_mm_dd_yy'),'\'];
								obj.savePath = fullfile(obj.saveRoot,...
										obj.animalName,...
										[obj.animalName,datestr(date,'_yyyy_mm_dd')]);
						else
								obj.savePath = obj.saveRoot;
						end
						obj.dataControl.savePathTxt = uicontrol(obj.dataControl.savePathPan,...
								'style','edit',...
								'tag','savefileedit',...
								'horizontalalignment','left',...
								'units','pixels',...
								'position',[10 70 200 20],...
								'string',obj.savePath);
						set([obj.dataControl.savePathTxt,...
								obj.dataControl.saveRootChgDirButt,...
								obj.dataControl.monkeyPop,...
								obj.dataControl.savePathAutoName],...
								'callback',@(src,evnt)savePathControlFcn(obj,src,evnt));
				end
		end
		
		
		
end