function processData()
% This function can be used to process data generated by the Matlab Imaging Program. 

% Go to Directory
cd(uigetdir(pwd,'Go to experiment'))

% Concatenate Data Files
dataSetFileNames = concatenateDataFileSets();

% Open Data Sets
for n=1:numel(dataSetFileNames)
	load(dataSetFileNames{n});
end

% Create 'DataProcessor' 
% -> A class with properties for storing data and methods for processing data
try
		obj = DataProcessor('videoFile',vidfiles,'behaviorFile',behfiles);
catch
		obj = DataProcessor;
end

% Run the 'export2LegacyFormat' Method of the DataProcessor Class
obj.export2LegacyFormat()
% or   >> export2LegacyFormat(obj)


