function camsettings = camsettings_hamamatsu_hardwaretrig()


trigconfig = struct(...
		  'TriggerType','hardware',...
		  'TriggerCondition','RisingEdge',...
		  'TriggerSource','SynchronousReadoutTrigger');
camsettings = {...
  'camAdaptor', 'hamamatsu',...
  'videoFormat',  'MONO16_BIN2x2_1024x1024_FastMode',...
  'triggerConfiguration', trigconfig};
