function bin_data = spatialBinData(data,binfactor)
% bin_data = spatialBinData(data,binfactor)
nrows = size(data,1)/binfactor;
ncols = size(data,2)/binfactor;
if ndims(data) > 2
	framedim = ndims(data); % last dimension
	nframes = size(data,framedim);
else
	nframes = 1;
end
try
	bin_data = zeros(nrows,ncols,1,nframes,class(data));
	for n = 1:nframes
		bin_data(:,:,1,n) = ...
			reshape(...
			sum(...
			reshape(...
			reshape(...
			sum(...
			reshape(...
			data(:,:,1,n),...
			binfactor,[]),...
			1),...
			nrows,[])',...
			binfactor,[]),...
			1),...
			ncols,[])';
	end
	% 	if nframes > 1
	% 				bin_data = reshape(bin_data,nrows,ncols,[],nframes);
	% 			else
	% 				bin_data = reshape(bin_data,nrows,ncols);
	% 			end
catch me
	keyboard
	fprintf('Error binning data')
		bin_data = data;
end
end



