function F = applyFunction2D( fcn , F, varargin)


[r, c, d3, d4] = size(F);

if nargin == 2
	F = reshape(...
		feval(fcn,...
		reshape(F, [r c*d3*d4]) ),...
		[r c d3 d4]);
else
	F = reshape(...
		feval(fcn,...
		reshape(F, [r c*d3*d4]),...
		varargin{:}),...
		[r c d3 d4]);
end



